### PR TITLE
Use src as string and not store path to avoid IFD

### PR DESCRIPTION
**Pull request by nmattia**

### CODE REVIEW

**Comment by hyperfekt** [comment]
This breaks building from derivations (if they haven't already been realized) instead of existing paths, any way to get that behavior back?

**Comment by nmattia** [comment]
@hyperfekt can you give a code example? I'll try to come up with a solution

**Comment by hyperfekt** [comment]
I tried adding `rust-analyzer` to the `buildInputs` but it did not help.
```
rust-analyzer = pkgs.fetchFromGitHub {
    owner = "rust-analyzer";
    repo = "rust-analyzer";
    rev = "ac7daf9cb9f6fcab5e561de2a43c6704868021e9";
    sha256 = "1x2cpyiyz6y7i52vqh3nk24vslazwd7a86pfzbnbwk4w0xry9ln2";
  };

  rust-analyzer-code = (napalm.buildPackage "${rust-analyzer}/editors/code" {
    name = "ra-lsp-0.0.1.zip";
    npmCommands = [
      "npm install"
      "patchShebangs node_modules"
      "node_modules/.bin/vsce package"
    ];
    installPhase = ''
      cp ra-lsp-0.0.1.vsix $out
    '';
  });
```

**Comment by hyperfekt** [comment]
Actually, it seems like this patch alone is not the culprit, and this usecase was never supported given `findPackageLock` uses `readDir`. This should probably be a feature request issue.

**Pull request merged**
